-- MySQL Script generated by MySQL Workbench
-- Fri Jan  6 03:22:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lucas_portfolio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lucas_portfolio` ;

-- -----------------------------------------------------
-- Schema lucas_portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lucas_portfolio` DEFAULT CHARACTER SET utf8 ;
USE `lucas_portfolio` ;

-- -----------------------------------------------------
-- Table `lucas_portfolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lucas_portfolio`.`persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `correo` VARCHAR(100) NULL,
  `fotoPerfil` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `lucas_portfolio`.`persona` (`correo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lucas_portfolio`.`tipo_empleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lucas_portfolio`.`tipo_empleo` (
  `id` INT NOT NULL,
  `nombre_tipo` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucas_portfolio`.`experiencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lucas_portfolio`.`experiencia_laboral` (
  `id` INT NOT NULL,
  `nombreEmpresa` VARCHAR(45) NULL,
  `esTrabajoActual` TINYINT NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `descripcion` VARCHAR(250) NULL,
  `persona_id` INT NOT NULL,
  `tipo_empleo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`, `tipo_empleo_id`),
  CONSTRAINT `fk_experiencia_laboral_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `lucas_portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_laboral_tipo_empleo1`
    FOREIGN KEY (`tipo_empleo_id`)
    REFERENCES `lucas_portfolio`.`tipo_empleo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_experiencia_laboral_persona_idx` ON `lucas_portfolio`.`experiencia_laboral` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_experiencia_laboral_tipo_empleo1_idx` ON `lucas_portfolio`.`experiencia_laboral` (`tipo_empleo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lucas_portfolio`.`tipo_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lucas_portfolio`.`tipo_curso` (
  `id` INT NOT NULL,
  `nombre_curso` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucas_portfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lucas_portfolio`.`educacion` (
  `id` INT NOT NULL,
  `nombrePlataforma` VARCHAR(45) NULL,
  `cursandoActual` TINYINT NULL,
  `fechaInicio` DATE NULL,
  `fechaFIN` DATE NULL,
  `descripcion` VARCHAR(400) NULL,
  `persona_id` INT NOT NULL,
  `tipo_curso_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`, `tipo_curso_id`),
  CONSTRAINT `fk_educacion_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `lucas_portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educacion_tipo_curso1`
    FOREIGN KEY (`tipo_curso_id`)
    REFERENCES `lucas_portfolio`.`tipo_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_educacion_persona1_idx` ON `lucas_portfolio`.`educacion` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_educacion_tipo_curso1_idx` ON `lucas_portfolio`.`educacion` (`tipo_curso_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
